# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100)),
                ('isActive', models.NullBooleanField(default=True)),
                ('isDelete', models.NullBooleanField(default=False)),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
                ('company_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyMemberDetail')),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
