# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('isActive', models.NullBooleanField(default=True)),
                ('isDelete', models.NullBooleanField(default=False)),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.NullBooleanField(default=True)),
                ('isDelete', models.NullBooleanField(default=False)),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
                ('menu_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.GroupTable')),
            ],
        ),
        migrations.CreateModel(
            name='MenuTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_string', models.CharField(max_length=100)),
                ('url_string', models.CharField(max_length=250)),
                ('group_permission_id', models.CharField(max_length=50)),
                ('has_child', models.NullBooleanField(default='null')),
                ('isActive', models.NullBooleanField()),
                ('isDelete', models.NullBooleanField()),
                ('insertUser', models.CharField(max_length=50)),
                ('insertDate', models.DateField(blank=True, null=True)),
                ('updateUser', models.CharField(blank=True, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, null=True)),
                ('project', models.CharField(max_length=100)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.MenuTable')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.NullBooleanField(default=True)),
                ('isDelete', models.NullBooleanField(default=False)),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.GroupTable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserDetail')),
            ],
        ),
        migrations.AddField(
            model_name='menugrouptable',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MenuTable'),
        ),
    ]
