# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='full_article',
            field=models.TextField(max_length=21845),
        ),
    ]
