# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('agenda', '0002_auto_20160929_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRemarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1200)),
                ('isActive', models.NullBooleanField(default=True)),
                ('isDelete', models.NullBooleanField(default=False)),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
                ('remarks_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
                ('remarks_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyMemberDetail')),
            ],
        ),
        migrations.CreateModel(
            name='MemberVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('pending', '0'), ('approve', '1'), ('disapprove', '2')], default='0', max_length=50)),
                ('isActive', models.NullBooleanField(default=True)),
                ('isDelete', models.NullBooleanField(default=False)),
                ('insertUser', models.CharField(default='system', max_length=50)),
                ('insertDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('updateUser', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updateDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('project', models.CharField(default='1', max_length=100)),
                ('vote_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
                ('vote_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyMemberDetail')),
            ],
        ),
    ]
