# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_memberremarks_membervote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberremarks',
            name='comment',
            field=models.BinaryField(max_length=1200),
        ),
    ]
