# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20161006_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='full_article',
            field=models.BinaryField(max_length=429496729),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='memberremarks',
            name='comment',
            field=models.TextField(max_length=1200),
        ),
    ]
