# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20161006_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='full_article',
            field=models.TextField(max_length=429496729),
        ),
    ]
