# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20161006_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membervote',
            name='vote',
            field=models.CharField(choices=[('pending', '0'), ('Endorsed', '1'), ('Opposed', '2')], default='0', max_length=50),
        ),
    ]
