# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20161008_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
