# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 05:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20161009_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymemberdetail',
            name='from_date',
            field=models.DateField(default=datetime.date(2016, 10, 9)),
        ),
        migrations.AddField(
            model_name='companymemberdetail',
            name='to_date',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
    ]
