# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20161009_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymemberdetail',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companymemberdetail',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
